[package]
name = "sysctlexplorer"
version = "0.2.0"
authors = ["Johannes Lundberg <johalun0@gmail.com>"]
edition = "2018"

[dependencies]
cursive_tree_view = "^0.7"
simplelog = "^0.6"
lazy_static = "^1.4"
log = "^0.4"
sysctl = "^0.4"
cursive = "^0.16"
